Repository umccr/data-portal-client, pull requests merged in 2022-02, with the labels that each got.

#90 Allow variants to be selected as tracks
  src/containers/IGV.tsx
  src/typings/index.d.ts
Labels: feature

#97 Bumped dependencies
  .eslintrc.json
  package.json
  start.sh
  yarn.lock
Labels: dependencies

#98 Bumped NodeJS 14 Fermium LTS
  .npmrc
  README.md
  buildspec.yml
  package.json
Labels: dependencies

#99 Updated IGV Subject data loading with subject endpoint
  src/containers/IGV.tsx
  src/containers/Run.js
Labels: change request

#100 Bumped Portal UI 0.4.0
  package.json
  yarn.lock
Labels: dependencies
