Repository umccr/data-portal-client, pull requests merged in 2022-08, with the labels that each got.

#140 add RNAsum button
  src/components/LaunchRNAsumReport.tsx
  src/containers/Subject.js
  src/utils/rnasum.js
Labels: feature

#141 Enable back FileViewer
  src/components/PreviewActionButton.tsx
  yarn.lock
Labels: feature

#142 css-fix
  src/components/LaunchRNAsumReport.tsx
Labels: feature

#135 add subject page checkpoint
  package.json
  src/App.tsx
  src/app.css
  src/components/DataActionButton/index.tsx
  src/components/DataTableWrapper/index.css
  src/components/DataTableWrapper/index.tsx
  src/components/FilePreviewButton/index.tsx
  src/components/JSONToTable/index.tsx
  src/components/ViewPresignedUrl/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/subjects/FileViewer/index.css
  src/containers/subjects/FileViewer/index.tsx
  src/containers/subjects/GDSSubjectDataTable/index.tsx
  src/containers/subjects/IGV/index.tsx
  src/containers/subjects/S3SubjectDataTable/index.tsx
  src/containers/subjects/SampleInformationTable/index.tsx
  src/containers/subjects/SubjectListTable/index.css
  src/containers/subjects/SubjectListTable/index.tsx
  src/containers/subjects/SubjectOverviewTable/index.tsx
  src/containers/subjects/SubjectSideBar/index.tsx
  src/containers/utils/TokenDialog/index.css
  src/containers/utils/TokenDialog/index.tsx
  src/layouts/Breadcrumbs/index.css
  src/layouts/Breadcrumbs/index.tsx
  src/layouts/MenuBar/index.tsx
  src/layouts/SideBar/index.css
  src/layouts/SideBar/index.tsx
  src/main.css
  src/pages/SignInPage/index.tsx
  src/pages/subjects/SubjectDataPage/index.css
  src/pages/subjects/SubjectDataPage/index.tsx
  src/pages/subjects/SubjectFileViewerPage/index.tsx
  src/pages/subjects/SubjectIGVPage/index.tsx
  src/pages/subjects/SubjectOverviewPage/index.tsx
  src/pages/subjects/SubjectTablePage/index.tsx
  src/providers/ToastProvider/index.tsx
  src/providers/UserProvider/index.tsx
  src/routes/index.tsx
  src/routes/subjects/index.tsx
  src/utils/api.ts
  src/utils/util.ts
  yarn.lock
Labels: feature, epic

#144 Metadata and LIMS Page Init
  src/components/DataTableWrapper/index.tsx
  src/containers/lims/LIMSTable/index.tsx
  src/containers/metadata/MetadataTable/index.css
  src/containers/metadata/MetadataTable/index.tsx
  src/pages/LIMS/index.tsx
  src/pages/metadata/index.tsx
  src/routes/index.tsx
Labels: feature, v2

#143 Update GPL trigger to use GDS (DRAGEN) inputs
  src/containers/Subject.js
Labels: change request, fix

#145 HomePage init
  src/containers/home/LimsCard/index.tsx
  src/containers/home/MetadataCard/index.tsx
  src/containers/home/SequenceCard/index.tsx
  src/containers/home/SubjectCard/index.tsx
  src/pages/Home/index.tsx
  src/pages/Metadata/index.tsx
  src/routes/index.tsx
Labels: feature, v2

#146 Reconfigure File Viewer
  package.json
  src/components/FilePreviewButton/index.tsx
  src/components/ViewPresignedUrl/index.css
  src/components/ViewPresignedUrl/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/subjects/GDSSubjectDataTable/index.tsx
  src/containers/subjects/S3SubjectDataTable/index.tsx
  yarn.lock
Labels: feature, v2

#147 Disabled LINX plotting Lambda
  src/config.js
  start.sh
Labels: change request

#148 Bumped dependencies
  package.json
  src/containers/Subject.js
  yarn.lock
Labels: dependencies

#149 Bumped version 1.1.0
  package.json
Labels: dependencies
