Repository umccr/data-portal-client, pull requests merged in 2022-05, with the labels that each got.

#117 Added GPL Report to Subject view
  buildspec.yml
  src/components/LaunchPadDialog.js
  src/config.js
  src/containers/Subject.js
  src/index.js
  start.sh
Labels: feature

#118 Added pre-launch BAM archive check for GPL Report trigger
  src/components/LaunchPadDialog.js
  src/containers/Subject.js
Labels: change request

#121 Added External Link to Drawer
  src/App.js
Labels: change request

#120 Change SignIn function
  src/App.js
Labels: change request

#119 Add file preview for PresignedUrl
  package.json
  src/components/PreviewActionButton.tsx
  src/containers/Subject.js
  yarn.lock
Labels: feature

#122 Added confirmation check for GPL Report trigger
  src/components/LaunchPadDialog.js
  src/containers/Subject.js
Labels: change request

#123 Update preview button
  src/components/PreviewActionButton.tsx
Labels: change request

#124 Add`.png` file previewer page
  src/Routes.js
  src/containers/FileViewer.tsx
  src/containers/Home.js
  src/containers/Subject.js
Labels: feature, epic

#125 Add filetype filters and css fix
  src/components/PreviewActionButton.tsx
  src/containers/FileViewer.tsx
  src/containers/Subject.js
Labels: feature
