Repository umccr/data-portal-client, pull requests merged in 2022-06, with the labels that each got.

#126 Added and switched default Subject Analysis Results to GDS
  src/containers/FileViewer.tsx
  src/containers/Run.js
  src/containers/Subject.js
Labels: feature, change request

#127 Bumped dependencies
  .gitignore
  package.json
  yarn.lock
Labels: dependencies

#128 Bumped version 1.0.0 and dependencies
  package.json
  yarn.lock
Labels: dependencies

#131 add v2 routing template
  index.html
  src/App.tsx
  src/Routes.tsx
  src/__Routes.tsx
  src/assets/unimelb.ico
  src/favicon.svg
  src/logo.svg
Labels: v2

#133 Add landing/signin page
  index.html
  src/App.tsx
  src/Routes.tsx
  src/assets/unimelb.ico
  src/pages/SignInPage.tsx
  src/providers/UserProvider.tsx
Labels: v2
