Repository umccr/data-portal-client, pull requests merged in 2022-12, with the labels that each got.

#199 Bug Fixes: Date && Cache
  src/api/gds.ts
  src/api/s3.ts
  src/components/DataActionButton/index.tsx
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/utils/TokenDialog/index.tsx
Labels: bug

#201 Bug Fixes: Date && Cache
  src/api/gds.ts
  src/api/s3.ts
  src/components/DataActionButton/index.tsx
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/utils/TokenDialog/index.tsx
Labels: bug, fix

#202 Bug Fixes: Date && Cache
  src/api/gds.ts
  src/api/s3.ts
  src/components/DataActionButton/index.tsx
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/utils/TokenDialog/index.tsx
Labels: bug, fix

#205 Change GPL Check from S3 to GDS
  src/components/JSONToTable/index.tsx
  src/containers/subjects/SubjectGPLLaunch/index.tsx
Labels: bug, fix

#207 Change GPL Check from S3 to GDS (#205)
  src/components/JSONToTable/index.tsx
  src/containers/subjects/SubjectGPLLaunch/index.tsx
Labels: bug, fix

#209 Misconfigured API
  src/components/DataActionButton/index.tsx
  src/containers/subjects/IGV/LoadSubjectDataButton.tsx
  src/containers/subjects/IGV/index.tsx
  src/containers/subjects/IGV/utils.ts
Labels: bug, v2

#210 Disable loading component
  src/components/DataActionButton/index.tsx
Labels: v2

#211 Text and CSS Update
  src/components/CircularLoaderWithText/index.tsx
  src/components/DataActionButton/index.tsx
  src/components/DataSearchFilterButton/index.tsx
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/home/LimsCard/index.tsx
  src/containers/home/MetadataCard/index.tsx
  src/containers/home/RunsCard/index.tsx
  src/containers/home/SequenceCard/index.tsx
  src/containers/home/SubjectCard/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: change request, v2

#213 CSS Update
  src/containers/home/LimsCard/index.tsx
  src/containers/home/MetadataCard/index.tsx
  src/containers/home/RunsCard/index.tsx
  src/containers/home/SequenceCard/index.tsx
  src/containers/home/SubjectCard/index.tsx
Labels: fix
