Repository umccr/data-portal-client, pull requests merged in 2022-10, with the labels that each got.

#153 Subject IGV Page
  package.json
  src/API/subject.ts
  src/containers/subjects/IGV/LoadCustomTrackDataButton.tsx
  src/containers/subjects/IGV/LoadSubjectDataButton.tsx
  src/containers/subjects/IGV/genomes.ts
  src/containers/subjects/IGV/index.tsx
  src/containers/subjects/IGV/utils.ts
  src/pages/subjects/SubjectIGVPage/index.tsx
  src/typings/index.d.ts
  yarn.lock
Labels: v2

#155 CSS Improvement
  src/containers/subjects/GDSSubjectDataTable/index.tsx
  src/containers/subjects/S3SubjectDataTable/index.tsx
  src/containers/subjects/SubjectListTable/index.tsx
  src/pages/subjects/SubjectLaunchPad/index.tsx
Labels: fix

#161 Removed legacy v1 placeholder code
  src/__App.js
  src/__Routes.tsx
  src/components/archive/ActionMenuButton.tsx
  src/components/archive/CopyButton.tsx
  src/components/archive/EnhancedTableHead.tsx
  src/components/archive/GDSActionMenuButton.tsx
  src/components/archive/HumanReadableFileSize.tsx
  src/components/archive/LaunchPadDialog.tsx
  src/components/archive/LimsRowDetailsDialog.tsx
  src/components/archive/PreviewActionButton.tsx
  src/components/archive/TablePagniationActionsWrapped.tsx
  src/pages/archive/AppBar.tsx
  src/pages/archive/FileViewer.tsx
  src/pages/archive/Home.tsx
  src/pages/archive/IGV.tsx
  src/pages/archive/LandingPage.tsx
  src/pages/archive/Run.tsx
  src/pages/archive/Search.tsx
  src/pages/archive/Subject.tsx
  src/utils/genomes.ts
Labels: v2

#164 Fixed vite build and bumped dependencies
  buildspec.yml
  index.html
  package.json
  start.sh
  vite.config.ts
  yarn.lock
Labels: dependencies, fix

#165 Issue #158 - Runs page
  src/api/run.ts
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/lims/LIMSTable/index.tsx
  src/containers/runs/RunOverviewTable/index.tsx
  src/containers/runs/RunSideBar/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/layouts/Breadcrumbs/index.tsx
  src/layouts/MenuBar/index.tsx
  src/layouts/SideBar/index.tsx
  src/pages/LIMS/index.tsx
  src/pages/runs/RunDataPage/index.tsx
  src/pages/runs/RunMetadataPage/index.tsx
  src/pages/runs/RunOverviewPage/index.tsx
  src/routes/index.tsx
  src/routes/runs/index.tsx
  src/routes/subjects/index.tsx
Labels: feature, v2

#167 issue#157 - Filter feature on Data in S3/GDS table.
  src/components/DataSearchFilterButton/index.tsx
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/lims/LIMSTable/index.tsx
  src/containers/metadata/MetadataTable/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/GDSSubjectDataTable/index.tsx
  src/containers/subjects/S3SubjectDataTable/index.tsx
  src/pages/subjects/SubjectDataPage/index.tsx
Labels: v2

#170 Reinstate igv desktop launch
  src/api/s3.ts
  src/components/DataActionButton/index.tsx
  src/components/JSONToTable/index.tsx
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/subjects/SubjectGPLLaunch/index.tsx
  src/containers/utils/TokenDialog/index.tsx
  src/providers/ToastProvider/index.tsx
Labels: v2, regression

#173 patch issue #166 - Open IGV Desktop
  src/components/DataActionButton/index.tsx
Labels: bug

#174 Reverted to Nodejs 14
  buildspec.yml
Labels: fix

#175 Deleted lower case rogue metadata directory
  src/pages/metadata/index.tsx
Labels: fix

#176 Align fields column in Subject Data Table
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: fix

#177 Upgraded to Nodejs 16
  buildspec.yml
  package.json
Labels: dependencies
