Repository umccr/data-portal-client, pull requests merged in 2023-07, with the labels that each got.

#270 Bumped dependencies
  package.json
  yarn.lock
Labels: dependencies

#271 Rolled back prettier
  package.json
  yarn.lock
Labels: dependencies

#272 Fixed code formats by prettier
  src/components/DataTableWrapper/index.css
  src/components/StyledJsonPretty/index.css
  src/components/ViewPresignedUrl/index.css
  src/components/search/PresetButton/index.css
  src/containers/metadata/MetadataTable/index.css
  src/containers/subjects/FileViewer/index.css
  src/containers/subjects/IGV/LoadCustomTrackDataButton.tsx
  src/containers/subjects/SubjectFeatureTable/index.css
  src/containers/subjects/SubjectListTable/index.css
  src/containers/subjects/SubjectRNASumLaunch/index.css
  src/containers/subjects/SubjectWGSTNLaunch/index.css
  src/containers/utils/TokenDialog/index.css
  src/layouts/Breadcrumbs/index.css
  src/layouts/MenuBar/index.css
  src/layouts/SideBar/index.css
  src/pages/subjects/SubjectDataPage/index.css
Labels: fix

#273 Fixed lint issues
  .eslintrc.json
  src/containers/subjects/IGV/LoadCustomTrackDataButton.tsx
  src/pages/SignInPage/index.tsx
  src/pages/subjects/SubjectLaunchPad/index.tsx
Labels: fix

#274 Added WTS fusions report to Analysis Results summary panel
  src/components/search/PresetDataFactory/index.ts
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: feature

#275 Added germline VCFs to Analysis Results summary panel
  src/components/search/PresetDataFactory/index.ts
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: feature

#276 Fix S3 Archival API
  src/components/RestoreArchiveObjectDialog/index.tsx
Labels: fix
