Repository umccr/data-portal-client, pull requests merged in 2023-02, with the labels that each got.

#224 Enhance IGV.js Custom Path Load
  src/api/gds.ts
  src/api/s3.ts
  src/components/DataActionButton/index.tsx
  src/containers/subjects/IGV/LoadCustomTrackDataButton.tsx
  src/containers/subjects/IGV/LoadSubjectDataButton.tsx
  src/containers/subjects/IGV/index.tsx
  src/containers/subjects/IGV/utils.ts
Labels: feature

#225 Update Copy Key/Path to URI
  src/components/DataActionButton/index.tsx
Labels: fix

#227 Bumped version 1.1.2 and dependencies
  package.json
  yarn.lock
Labels: dependencies

#228 Fixed Portal v1 IGV.js loading track support for htsget-rs ID style
  src/containers/IGV.tsx
Labels: fix

#229 S3 Bam Restoration Feature
  src/api/s3.ts
  src/components/DataActionButton/index.tsx
  src/components/GeneratePresignedDialog/index.tsx
  src/components/OpenInIgvDialog/index.tsx
  src/components/RestoreArchiveObjectDialog/index.tsx
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/subjects/IGV/LoadSubjectDataButton.tsx
  src/containers/utils/DataActionButton/index.tsx
Labels: feature

#230 Improved File Viewer
  src/components/CircularLoaderWithText/index.tsx
  src/components/DataSearchFilterButton/index.tsx
  src/components/FilePreviewButton/index.tsx
  src/components/ViewPresignedUrl/index.css
  src/components/ViewPresignedUrl/index.tsx
Labels: feature

#233 Request inline presign for GDS
  src/api/gds.ts
  src/components/FilePreviewButton/index.tsx
  src/components/GeneratePresignedDialog/index.tsx
Labels: feature

#231 WGS T/N Workflow Launch
  package.json
  src/api/fastq.ts
  src/api/metadata.ts
  src/api/pairing.ts
  src/components/CircularLoaderWithText/index.tsx
  src/components/FilePreviewButton/index.tsx
  src/components/GeneratePresignedDialog/index.tsx
  src/components/StyledJsonPretty/index.css
  src/components/StyledJsonPretty/index.tsx
  src/components/ViewPresignedUrl/index.css
  src/components/ViewPresignedUrl/index.tsx
  src/config.ts
  src/containers/home/MetadataCard/index.tsx
  src/containers/metadata/MetadataTable/index.tsx
  src/containers/subjects/SubjectWGSTNLaunch/aws.ts
  src/containers/subjects/SubjectWGSTNLaunch/index.css
  src/containers/subjects/SubjectWGSTNLaunch/index.tsx
  src/pages/subjects/SubjectLaunchPad/index.tsx
  src/routes/subjects/index.tsx
  yarn.lock
Labels: feature

#234 RNAsum Trigger Refactor && Other Refactors
  src/api/subject.ts
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/subjects/SampleInformationTable/index.tsx
  src/containers/subjects/SubjectGPLLaunch/index.tsx
  src/containers/subjects/SubjectOverviewTable/index.tsx
  src/containers/subjects/SubjectRNASumLaunch/aws.ts
  src/containers/subjects/SubjectRNASumLaunch/index.tsx
Labels: change request

#236 Divert API to lambda Invoke for RNAsum
  package.json
  src/components/LaunchRNAsumReport.tsx
  src/config.js
  yarn.lock
Labels: change request, fix
