Repository umccr/data-portal-client, pull requests merged in 2023-03, with the labels that each got.

#237 GPL Refactor
  buildspec.yml
  src/components/ViewPresignedUrl/index.tsx
  src/config.ts
  src/containers/subjects/SubjectGPLLaunch/aws.ts
  src/containers/subjects/SubjectGPLLaunch/index.tsx
  src/containers/subjects/SubjectRNASumLaunch/index.tsx
  src/containers/subjects/SubjectWGSTNLaunch/index.tsx
  src/main.tsx
  start.sh
Labels: change request

#238 [V1] GPL Trigger Refactor
  buildspec.yml
  src/config.js
  src/containers/Subject.js
  src/index.js
  start.sh
Labels: change request

#239 HTML Presigned URL Component Proposal
  src/components/ViewPresignedUrl/index.tsx
Labels: fix

#240 Updated tumor normal trigger pairing payload
  src/api/pairing.ts
  src/containers/subjects/SubjectWGSTNLaunch/index.tsx
Labels: change request

#241 Allowed RNAsum trigger on multiple transcriptome output
  src/containers/subjects/SubjectRNASumLaunch/index.tsx
Labels: change request

#242 Reinstated Subject feature panel with circos plot
  src/containers/subjects/SubjectFeatureTable/index.tsx
  src/main.css
  src/pages/subjects/SubjectOverviewPage/index.tsx
Labels: fix, regression

#243 Added TSO tsv output in Subject analysis summary panel
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: change request

#244 [V1] Added TSO tsv output in Subject analysis summary panel
  src/containers/Subject.js
Labels: change request

#245 Adjusted round 1 of various UI and UX tinkering
  src/app.css
  src/components/CircularLoaderWithText/index.tsx
  src/components/DataTableWrapper/index.tsx
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/metadata/MetadataTable/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/FileViewer/index.tsx
  src/containers/subjects/IGV/LoadCustomTrackDataButton.tsx
  src/containers/subjects/IGV/LoadSubjectDataButton.tsx
  src/containers/subjects/IGV/index.tsx
  src/containers/subjects/SampleInformationTable/index.tsx
  src/containers/subjects/SubjectGPLLaunch/index.tsx
  src/containers/subjects/SubjectListTable/index.tsx
  src/containers/subjects/SubjectRNASumLaunch/index.css
  src/containers/subjects/SubjectRNASumLaunch/index.tsx
  src/containers/subjects/SubjectWGSTNLaunch/index.tsx
  src/layouts/MenuBar/index.css
  src/layouts/MenuBar/index.tsx
  src/main.css
  src/pages/LIMS/index.tsx
Labels: fix

#246 Implemented initial approach for LIMS DataTable Filtering
  src/api/lims.ts
  src/containers/lims/LIMSTable/index.tsx
  src/containers/lims/LimsSideBar/index.tsx
  src/containers/runs/RunSideBar/index.tsx
  src/containers/subjects/SubjectSideBar/index.tsx
  src/layouts/SideBar/index.css
  src/layouts/SideBar/index.tsx
  src/pages/Home/index.tsx
  src/pages/runs/RunLIMSPage/index.tsx
Labels: feature

#247 Adjusted round 2 of various UI and UX tinkering
  src/App.tsx
  src/api/run.ts
  src/components/DataSearchFilterButton/index.tsx
  src/components/search/PresetButton/index.css
  src/components/search/PresetButton/index.tsx
  src/components/search/PresetDataFactory/index.ts
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/lims/LIMSTable/index.tsx
  src/containers/runs/RunOverviewTable/index.tsx
  src/containers/runs/RunSideBar/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/SampleInformationTable/index.tsx
  src/containers/subjects/SubjectWGSTNLaunch/index.tsx
  src/layouts/MenuBar/index.tsx
  src/pages/runs/RunDataPage/index.tsx
  src/pages/runs/RunLIMSPage/index.tsx
  src/pages/runs/RunOverviewPage/index.tsx
  src/pages/subjects/SubjectDataPage/index.tsx
  src/routes/runs/index.tsx
Labels: change request

#248 Implemented open Report in inline browser tab
  src/api/gds.ts
  src/api/s3.ts
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/providers/ToastProvider/index.tsx
Labels: change request

#249 Implemented Skeleton loader components
  src/components/skel/FeatureSkeleton/index.tsx
  src/components/skel/OverviewSkeleton/index.tsx
  src/components/skel/TableSkeleton/index.tsx
  src/containers/subjects/SampleInformationTable/index.tsx
  src/containers/subjects/SubjectFeatureTable/index.css
  src/containers/subjects/SubjectFeatureTable/index.tsx
  src/containers/subjects/SubjectOverviewTable/index.tsx
  src/containers/subjects/SubjectWGSTNLaunch/index.tsx
Labels: feature

#250 [V1] Fixed GDS PreSigned URL with inline opening in Browser new tab
  src/components/GDSActionMenuButton.js
  src/components/PreviewActionButton.tsx
  src/containers/Run.js
  src/containers/Subject.js
Labels: fix

#251 [V1] Bumped dependencies
  package.json
  yarn.lock
Labels: dependencies

#252 Bumped dependencies
  package.json
  yarn.lock
Labels: dependencies
