Repository umccr/data-portal-client, pull requests merged in 2023-08, with the labels that each got.

#278 Bumped dependencies
  package.json
  yarn.lock
Labels: dependencies

#279 feat: Trigger Star Alignment from UI
  package.json
  src/api/fastq.ts
  src/app.css
  src/containers/subjects-launch/SubjectGPLLaunch/aws.ts
  src/containers/subjects-launch/SubjectGPLLaunch/index.tsx
  src/containers/subjects-launch/SubjectRNASumLaunch/aws.ts
  src/containers/subjects-launch/SubjectRNASumLaunch/index.css
  src/containers/subjects-launch/SubjectRNASumLaunch/index.tsx
  src/containers/subjects-launch/SubjectRNASumLaunch/utils.ts
  src/containers/subjects-launch/SubjectWGSTNLaunch/aws.ts
  src/containers/subjects-launch/SubjectWGSTNLaunch/index.css
  src/containers/subjects-launch/SubjectWGSTNLaunch/index.tsx
  src/containers/subjects-launch/SubjectWTSStarAlignment/aws.ts
  src/containers/subjects-launch/SubjectWTSStarAlignment/index.tsx
  src/pages/subjects/SubjectLaunchPad/index.tsx
  yarn.lock
Labels: feature

#280 feat: Oncoanalyser Trigger
  src/api/lims.ts
  src/api/subject.ts
  src/components/CircularLoaderWithText/index.tsx
  src/components/JSONToTable/index.tsx
  src/containers/subjects-launch/SubjectMetadata/index.tsx
  src/containers/subjects-launch/SubjectOncoanalyserLaunch/aws.ts
  src/containers/subjects-launch/SubjectOncoanalyserLaunch/index.tsx
  src/containers/subjects-launch/SubjectOncoanalyserLaunch/inputModes/WGSDragenInput.tsx
  src/containers/subjects-launch/SubjectOncoanalyserLaunch/inputModes/WTSStarAlignInput.tsx
  src/containers/subjects-launch/SubjectWGSTNLaunch/index.tsx
  src/containers/subjects-launch/SubjectWTSStarAlignment/index.tsx
  src/containers/subjects-launch/utils/ConfirmationDialog.tsx
  src/pages/subjects/SubjectLaunchPad/index.tsx
Labels: feature, epic

#282 Bump `primereact` 9.6.2
  package.json
  src/components/DataTableWrapper/index.tsx
  src/components/GeneratePresignedDialog/index.tsx
  src/components/JSONToTable/index.tsx
  src/components/RestoreArchiveObjectDialog/index.tsx
  src/components/ViewPresignedUrl/index.tsx
  src/containers/lims/LIMSTable/index.tsx
  src/containers/metadata/MetadataTable/index.tsx
  src/containers/runs/RunSideBar/index.tsx
  src/containers/subjects-launch/SubjectMetadata/index.tsx
  src/containers/subjects-launch/SubjectRNASumLaunch/index.tsx
  src/containers/subjects-launch/SubjectWGSTNLaunch/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/subjects/IGV/LoadSubjectDataButton.tsx
  src/containers/subjects/IGV/index.tsx
  src/containers/subjects/SubjectSideBar/index.tsx
  src/containers/utils/TokenDialog/index.tsx
  src/providers/ToastProvider/index.tsx
  yarn.lock
Labels: dependencies

#281 Fix: GPL Eligibility Check && Some UI Fixes
  src/containers/subjects-launch/SubjectGPLLaunch/aws.ts
  src/containers/subjects-launch/SubjectGPLLaunch/index.tsx
  src/containers/subjects-launch/SubjectOncoanalyserLaunch/index.tsx
  src/containers/subjects-launch/SubjectRNASumLaunch/aws.ts
  src/containers/subjects-launch/SubjectRNASumLaunch/index.tsx
  src/containers/subjects-launch/SubjectWGSTNLaunch/index.tsx
  src/containers/subjects-launch/SubjectWTSStarAlignment/index.tsx
  src/containers/subjects-launch/utils/ConfirmationDialog.tsx
  src/pages/subjects/SubjectLaunchPad/index.tsx
Labels: fix

#284 Deprecation Alert
  package.json
  src/App.js
  src/containers/AppBar.js
  src/index.js
  yarn.lock
Labels: documentation, dependencies

#288 FE Chores
  src/components/DataTableWrapper/index.css
  src/components/ViewPresignedUrl/index.css
  src/components/ViewPresignedUrl/index.tsx
  src/components/search/PresetButton/index.tsx
  src/components/search/PresetDataFactory/index.ts
  src/containers/lims/LIMSTable/index.tsx
  src/containers/subjects/SampleInformationTable/index.tsx
  src/containers/subjects/SubjectFeatureTable/index.tsx
  src/layouts/SideBar/index.tsx
  src/pages/subjects/SubjectOverviewPage/index.tsx
Labels: feature
