Repository umccr/data-portal-client, pull requests merged in 2024-07, with the labels that each got.

#337 Bumped dependencies
  .eslintignore
  .eslintrc.json
  .gitguardian.yaml
  .pre-commit-config.yaml
  .yarn/plugins/@yarnpkg/plugin-outdated.cjs
  .yarn/releases/yarn-4.0.2.cjs
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
  README.md
  buildspec.yml
  eslint.config.mjs
  package.json
  src/containers/gds/GDSDataTable/index.tsx
  src/containers/lims/LIMSTable/index.tsx
  src/containers/metadata/MetadataTable/index.tsx
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/SubjectListTable/index.tsx
  src/layouts/MenuBar/index.css
  src/layouts/SideBar/index.css
  yarn.lock
Labels: dependencies, fix

#327 Feature: add spot in the analysis results panel
  src/api/subject.ts
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: feature

#338 hotfix for cttsov2 portalRunId
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: bug, fix

#343 Fix SideBar Menu Click Reload
  src/containers/subjects/SubjectSideBar/index.tsx
Labels: fix

#345 add gvcf file for cttsov2 and add content disposition header for s3 p…
  src/api/s3.ts
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: change request, fix

#346 Feat: Allow IGV open in presigned mode in S3
  eslint.config.mjs
  src/api/s3.ts
  src/components/OpenInIgvDialog/gds.ts
  src/components/OpenInIgvDialog/index.tsx
  src/components/OpenInIgvDialog/s3.ts
  src/components/OpenInIgvDialog/utils.ts
  src/containers/s3/S3DataTable/index.tsx
  src/containers/subjects/AnalysisResultTable/index.tsx
  src/containers/subjects/IGV/index.tsx
  src/containers/subjects/IGV/utils.ts
  src/containers/utils/DataActionButton/index.tsx
Labels: feature

#347 Tuned run data view for ICAv2 pipeline primary output
  src/components/search/PresetDataFactory/index.ts
  src/containers/utils/DataActionButton/index.tsx
Labels: change request

#348 Improved Analysis Results panel WGS sash tab UX behaviours
  src/api/s3.ts
  src/components/search/PresetDataFactory/index.ts
  src/containers/subjects/AnalysisResultTable/index.tsx
Labels: fix

#349 Bumped dependencies
  package.json
  yarn.lock
Labels: dependencies
